export enum NAVIGATION_ENDPOINT {
  EXERCISES = "EXERCISES",
  CREATE_EXERCISE = "CREATE_EXERCISE",
  OVERVIEW = "OVERVIEW",
}

export const URL_PATH: Record<NAVIGATION_ENDPOINT, string> = {
  [NAVIGATION_ENDPOINT.EXERCISES]: "/exercises",
  [NAVIGATION_ENDPOINT.CREATE_EXERCISE]: "/exercises/create",
  [NAVIGATION_ENDPOINT.OVERVIEW]: "/",
};
