export enum NAVIGATION_ENDPOINT {
  EXERCISES = "EXERCISES",
  CREATE_EXERCISE = "CREATE_EXERCISE",
  OVERVIEW = "OVERVIEW",
  SESSION = "SESSION",
}

export const URL_PATH: Record<NAVIGATION_ENDPOINT, string> = {
  [NAVIGATION_ENDPOINT.EXERCISES]: "/exercises",
  [NAVIGATION_ENDPOINT.CREATE_EXERCISE]: "/exercises/create",
  [NAVIGATION_ENDPOINT.OVERVIEW]: "/",
  [NAVIGATION_ENDPOINT.SESSION]: "/sessions",
};

export enum EXERCISE_FORMAT {
  SINGLE_INTERVAL = "SINGLE_INTERVAL",
}

export enum MUSICAL_INTERVAL {
  UNISON = "UNISON",
  MINOR_2ND = "MINOR_2ND",
  MAJOR_2ND = "MAJOR_2ND",
  MINOR_3RD = "MINOR_3RD",
  MAJOR_3RD = "MAJOR_3RD",
  PERFECT_4TH = "PERFECT_4TH",
  TRITONE = "TRITONE",
  PERFECT_5TH = "PERFECT_5TH",
  MINOR_6TH = "MINOR_6TH",
  MAJOR_6TH = "MAJOR_6TH",
  MINOR_7TH = "MINOR_7TH",
  MAJOR_7TH = "MAJOR_7TH",
  PERFECT_8TH = "PERFECT_8TH",
}

export enum INTERVAL_TEXTURE {
  STACKED = "STACKED",
  ASCENDING = "ASCENDING",
  DESCENDING = "DESCENDING",
}
