export enum NAVIGATION_ENDPOINT {
  EXERCISES = "EXERCISES",
  OVERVIEW = "OVERVIEW",
}

export const URL_PATH: Record<NAVIGATION_ENDPOINT, string> = {
  [NAVIGATION_ENDPOINT.EXERCISES]: "/exercises",
  [NAVIGATION_ENDPOINT.OVERVIEW]: "/",
};
