export enum EventType {
  DRAG = "DRAG",
  DROP = "DROP",
  CHANGE_POSITION = "CHANGE_POSITION",
  START_DRAGGING = "START_DRAGGING",
  ELEMENT_CREATED = "ELEMENT_CREATED",
  ELEMENT_DELETED = "ELEMENT_DELETED",
}
